### ISSUE TITLE
Error: Cannot read property 'prefix' of undefined in views\dashboard\manage.ejs:23

### ISSUE THREAD

**Issue by devilAPI** [NTMNathan/discord-dashboard#3]
```
TypeError: C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\views\dashboard\manage.ejs:23
    21|         <div class="mb-3">
    22|             <label for="prefix" class="form-label text-light">Prefix</label>
 >> 23|             <input type="text" class="form-control" name="prefix" placeholder="<%= settings.prefix %>">
    24|             <br>
    25|             <button type="submit" class="btn btn-success"><i class="fas fa-paper-plane"></i> Save Changes</button>
    26|             <br>

Cannot read property 'prefix' of undefined
    at eval (eval at compile (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\ejs\lib\ejs.js:662:12), <anonymous>:38:35)
    at manage (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\ejs\lib\ejs.js:692:17)
    at tryHandleCache (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\ejs\lib\ejs.js:272:36)
    at View.exports.renderFile [as engine] (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\express\lib\response.js:1012:7)
    at C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\routes\dashboard.js:82:9
    at Layer.handle [as handle_request] (C:\Users\entro\Downloads\discord-dashboard-master\discord-dashboard-master\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by NTMNathan** [comment]
You need to make sure that the database has been initialized. You can do this by sending a message in the channel the bot is in.

Next time, please try to be descriptive of what the bug is as opposed to just sending code only. Thanks!
